name: news_arch
description: Simple application to demonstrate the new app

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3

  # comparing dart objects
  equatable: ^2.0.5

  #service location
  get_it: ^7.6.4

  #dateformat
  intl: ^0.19.0

  #database
  floor: ^1.4.2

  #make request to api
  retrofit: ^4.0.3

  #Hooks
  flutter_hooks: ^0.18.3

  #chached image
  cached_network_image: ^3.2.0

  #icon
  ionicons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^8.0.6
  floor_generator: 1.4.2
  build_runner: 2.4.1

flutter:
  uses-material-design: true
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/roboto/Roboto-Regular.ttf
         - asset: assets/fonts/roboto/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/roboto/Roboto-Light.ttf
           weight: 300